language: node_js
node_js:
  - "10"
env:
  - CI=true
cache:
  yarn: true
  directories:
    - node_modules
git:
  depth: 5
script:
  - yarn format:ci
  - yarn test:cover
  - yarn build
  - yarn build:docz
after_success:
  - $TRAVIS_BRANCH == "master" && yarn run deploy-docs
  - $TRAVIS_BRANCH == "master" && yarn run semantic-release
