language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
node_js:
  - "10"
env:
  - CI=true
cache: yarn
git:
  depth: 5
script:
  - yarn test:cover && yarn build:docz
after_success:
  - npm run deploy-docs
  # - npm run semantic-release
