language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
node_js:
  - "10"
env:
  - CI=true
cache:
  yarn: true
  directories:
    - node_modules
git:
  depth: 5
script:
  - yarn format:ci
  - yarn test:cover
  - yarn build
  - yarn build:docz
after_success:
  - yarn run deploy-docs
  - yarn run semantic-release
